// <auto-generated />
namespace WebApplication1_Web.API_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Asd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Asd));
        
        string IMigrationMetadata.Id
        {
            get { return "202209201039580_Asd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
